### ISSUE TITLE
Is there anyway of using custom progress bar class for loading indicator?

### ISSUE THREAD

**Issue by xyrintech** [swimlane/ngx-datatable#1210]
Currently, making loadingIndicator to true loads ProgressBarComponent. 

Is there anyway we can assign out own temple or class for progress bar?

**Comment by carlosleopoldo** [comment]
I did it with those SCSS styles:

```scss
.ngx-datatable
  .datatable-body {
    .progress-linear {
      display: block;
      position: relative;
      width: 100%;
      height: 8px;
      padding: 0;
      margin: 0;
      position: absolute;
      .container {
        display: block;
        position: relative;
        overflow: hidden;
        width: 100%;
        height: 8px;
        -webkit-transform: translate(0, 0) scale(1, 1);
        transform: translate(0, 0) scale(1, 1);
        background-color: $info;
        .bar {
          transition: all .15s linear;
          -webkit-animation: query 0.5s infinite cubic-bezier(0.39, 0.575, 0.565, 1);
          animation: query 0.5s infinite cubic-bezier(0.39, 0.575, 0.565, 1);
          transition: -webkit-transform .15s linear;
          transition: transform .15s linear;
          background-color: $primary;
          position: absolute;
          left: 0;
          top: 0;
          bottom: 0;
          width: 100%;
          height: 8px;
        }
      }
    }
    datatable-progress + datatable-scroller.datatable-scroll {
      display: none;
    }
}
/**
 * Progress bar animations
 */
@keyframes query {
  0% {
    opacity: 1;
    transform: translateX(35%) scale(0.3, 1);
  }
  100% {
    opacity: 0;
    transform: translateX(-50%) scale(0, 1);
  }
}

```
