### ISSUE TITLE
Vertical scrollbar in footer on bootstrap and dark theme

### ISSUE THREAD

**Issue by Dorus** [swimlane/ngx-datatable#2104]
I'm submitting a bug report

**Current behavior**

See https://swimlane.github.io/ngx-datatable/#bootstrap

![image](https://user-images.githubusercontent.com/4461459/181004584-cb6faf01-1f1d-44f0-933b-e8a3d6222c20.png)

There is a vertical scrollbar in the footer on the bootstrap theme.

**Expected behavior**

No needless scrollbar

**Reproduction of the problem**

Visit https://swimlane.github.io/ngx-datatable/#bootstrap

**What is the motivation / use case for changing the behavior?**

Less ugly

**Please tell us about your environment:**

Latest Chrome. Also reproducible in latest Edge, Firefox. Windows 11.

- **Table version:**
20.0.0

- **Angular version:**
14

- **Browser:**
- Latest Chrome. Also reproducible in latest Edge, Firefox.

- **Language:** Not relevant

**Comment by Dorus** [comment]
I fixed this locally by adding the following css:
```Css
.ngx-datatable.bootstrap .datatable-footer .page-count {
  line-height: 40px;
  height: 40px;
}

.ngx-datatable.bootstrap .datatable-footer .datatable-pager ul li {
  margin: 9px 0px;
}
```
