### ISSUE TITLE
How to give height auto for row detail

### ISSUE THREAD

**Issue by pranavsreedhar92** [swimlane/ngx-datatable#544]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request => Please do not submit support request here
```

**Current behavior**
Need help for giving height auto for row details section. 

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your 
OS : Windows
IDE : NetBeans

* **Table version:** 0.7.x
6.1.2

* **Angular version:** 2.0.x
2.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by norenma** [comment]
Hello, did you find a solution for this? I have the same problem.

**Comment by pranavsreedhar92** [comment]
Use [rowHeight]="'auto'"

**Comment by Humberd** [comment]
It doesn't work for me

**Comment by lesliesu** [comment]
I have got the same issue. I need to set scrollbarV and scrollbarH to true, meanwhile show row details (which means I need to set [rowHeight]="'auto'"), but it will give me error if I combine all these options together.

**Comment by Humberd** [comment]
I managed to do it. You need to add this in your global styles:

```scss
ngx-datatable {
   .auto-details-height {
      .datatable-row-wrapper {
         height: unset !important;
         .datatable-row-detail {
            height: unset !important;
         }
      }
   }
}
```

**Comment by bluecaret** [comment]
I'm not able to get this working either.. The CSS provided by @Humberd doesn't work for me.
The amount of hard coded pixel sizes in this plugin is insane, very difficult to make a responsive app with this.

**Comment by resting** [comment]
Did a slight modification to the solution by @Humberd to make it work for me.
I didn't specify `[rowHeight]` in `ngx-datatable-row-detail` either.

```css
ngx-datatable {
  .datatable-row-wrapper {
    height: unset !important;
    .datatable-row-detail {
      height: unset !important;
    }
  }
}
```
