### ISSUE TITLE
how can i apply bootstrap table theme to ngx-datatable ??   

### ISSUE THREAD

**Issue by kfaiad** [swimlane/ngx-datatable#635]
i using ngx-datatable but i need to using bootstrap theme ( classes ) and  i searched a lot and cant find the way to apply bootstrap classes to ngx-datatable  could you help me please ??

**Comment by adammedford** [comment]
Taken literally, what you're asking for isn't possible. What you (or someone else) can do, however, is write a stylesheet using excerpts from bootstrap around ngx-datatable's themeing framework. I've done it; its pretty simple since all you really care about is padding, backgrounds and font weights.

https://swimlane.gitbooks.io/ngx-datatable/content/introduction/themes.html

FYI: I'm not affiliated with this project.

**Comment by adammedford** [comment]
To give you an example. A bootstrap 3 header cell might look like

```
.datatable-header-cell {
vertical-align: bottom;
border-bottom: 2px solid #ddd;
padding: 8px;
line-height: 1.42857143;
}
```

**Comment by amcdnl** [comment]
Please fill out the form in the future.

In order to apply bootstrap styles, you just need to create a new theme for bootstrap. Checkout material theme for direction.

**Comment by kfaiad** [comment]
@adammedford Thanks for your help that is what i will done in the project create a bootstrap style sheet for the table :+1: 

@amcdnl could you be more clear i don't understand what you mean in your reply

**Comment by borislitvak** [comment]
@kfaiad Could you please share it with us?

**Comment by agil-NUBBA** [comment]
there goes my aproach, about 20 minutes (took dark as start point), hope you find usefull and kepp improving it.

 ```css
.ngx-datatable.bootstrap {
    box-shadow: none;
    font-size: 13px;
}
.ngx-datatable.bootstrap .datatable-header {
    height: unset !important;
}
.ngx-datatable.bootstrap .datatable-header .datatable-header-cell {
    vertical-align: bottom;
    padding: 0.75rem;
    border-bottom: 1px solid #d1d4d7;
}
.ngx-datatable.bootstrap .datatable-header .datatable-header-cell .datatable-header-cell-label {
    line-height: 24px;
}
.ngx-datatable.bootstrap .datatable-body {

}
.ngx-datatable.bootstrap .datatable-body .datatable-body-row {
    padding: 0.75rem;
    vertical-align: top;
    border-top: 1px solid #d1d4d7;
}
.ngx-datatable.bootstrap .datatable-body .datatable-body-row.datatable-row-even {
    background-color: rgba(0, 0, 0, 0.05);
}
.ngx-datatable.bootstrap .datatable-body .datatable-body-row .datatable-body-cell {
    text-align: left;
    vertical-align: top;
}
.ngx-datatable.bootstrap .datatable-body .datatable-body-row.active {
    background-color: #1483ff;
    color: #FFF;
}
.ngx-datatable.bootstrap .datatable-footer {
    background: #424242;
    color: #ededed;
    margin-top: -1px;
}
.ngx-datatable.bootstrap .datatable-footer .page-count {
    line-height: 50px;
    height: 50px;
    padding: 0 1.2rem;
}
.ngx-datatable.bootstrap .datatable-footer .datatable-pager {
    margin: 0 10px;
    vertical-align: top;
}
.ngx-datatable.bootstrap .datatable-footer .datatable-pager ul li {
    margin: 10px 0px;
}
.ngx-datatable.bootstrap .datatable-footer .datatable-pager ul li:not(.disabled).active a,
.ngx-datatable.bootstrap .datatable-footer .datatable-pager ul li:not(.disabled):hover a {
    background-color: #545454;
    font-weight: bold;
}
.ngx-datatable.bootstrap .datatable-footer .datatable-pager a {
    height: 22px;
    min-width: 24px;
    line-height: 22px;
    padding: 0;
    border-radius: 3px;
    margin: 0 3px;
    text-align: center;
    vertical-align: top;
    text-decoration: none;
    vertical-align: bottom;
    color: #ededed;
}
.ngx-datatable.bootstrap .datatable-footer .datatable-pager .datatable-icon-left,
.ngx-datatable.bootstrap .datatable-footer .datatable-pager .datatable-icon-skip,
.ngx-datatable.bootstrap .datatable-footer .datatable-pager .datatable-icon-right,
.ngx-datatable.bootstrap .datatable-footer .datatable-pager .datatable-icon-prev {
    font-size: 18px;
    line-height: 27px;
    padding: 0 3px;
}
```
