### ISSUE TITLE
DataTablePagerComponent custom number of displayed pages.

### ISSUE THREAD

**Issue by t-p-l-k** [swimlane/ngx-datatable#802]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
DataTablePagerComponent can't be configured to display custom number of pages. Currently it's hardcoded to display 5 pages always.
```javascript
const maxSize = 5;
```

**Expected behavior**
User should be able to set a custom number of elements to be displayed which fits his project requirements.

I already implemented it in my current project by adding a variable which can be passed from the template. If anyone interested I can create a pull request.

**Comment by mvhecke** [comment]
@t-p-l-k I don't really get the use case, could you be more specific? When external paging is enabled the page size is automatically calculated, so I don't get the need to expose this.

**Comment by MorlaRamakrishna** [comment]
@mvhecke How can we control automatic calculation of the pageSize. Because it forcing to miscalculate the number pages.

**Comment by t-p-l-k** [comment]
@mvhecke here's an example:

![image](https://user-images.githubusercontent.com/20531968/26927992-ef319300-4c5c-11e7-820c-e573f9160eba.png)

Pager displays 5 pages and it's okay when you only have pagination in the footer. But what if we need extra information there?

![image](https://user-images.githubusercontent.com/20531968/26928419-b8d7214c-4c5e-11e7-9515-510615b2ba55.png)

Well, it seems logical to reduce pager's width so it doesn't take 1/3 of footer's width.

![image](https://user-images.githubusercontent.com/20531968/26928486-edb9b780-4c5e-11e7-829e-72f189764453.png)

Another use case is a mobile layout where viewport width causes default pager to wrap.

![image](https://user-images.githubusercontent.com/20531968/26928605-65dfabac-4c5f-11e7-912b-7d6bac570f93.png)

**Comment by t-p-l-k** [comment]
Last use case can be solved with css media queries but anyway.

**Comment by mvhecke** [comment]
Aah, a very good example. Now I get why you would want this, should be pretty easy to expose this.

**Comment by t-p-l-k** [comment]
Offtopic:
@mvhecke btw, I don't understand how can I change row limit dynamically. You've mentioned somewhere that datatable uses OnPush change detection strategy but it doesn't work with limit value (works for pager maxSize without any extra work, I just switched constant maxSize with an input variable). Should I create a new issue to solve this?

**Comment by t-p-l-k** [comment]
Oh, I think I figured it out: https://plnkr.co/edit/wRWlit

**Comment by dylandrollut** [comment]
@t-p-l-k do you mind explaining how you went about finding your solution? I modified it to work for a drop-down menu to choose the number of items per page, but I don't fully understand what's going on code wise.

**Comment by rahul-winner** [comment]
@t-p-l-k 
I am little curious to know how could we get selection box in the footer to allow changing the pageSize. Please see the highlighted section in image. 
![image](https://user-images.githubusercontent.com/4982751/27065514-57e48062-501b-11e7-8f85-32cd53a75b73.png)


I'd tried to achieve it however could not make it work. I've seen you got good hold on this code, could you please help me out achieve this.

Thanks. Rahul

**Comment by rahul-winner** [comment]
Adding to my query : 

@mvhecke  Would it be a good idea to have this feature **[**allow to change page size from footer**]** OOTB !

**Comment by t-p-l-k** [comment]
@rahul-winner sure, here's working example: https://plnkr.co/edit/ym689j
You can create custom footer template and move select element there:
```html
<ngx-datatable-footer>
  <ng-template
    ngx-datatable-footer-template
    let-rowCount="rowCount"
    let-pageSize="pageSize"
    let-selectedCount="selectedCount"
    let-curPage="curPage"
    let-offset="offset"
  >
    <div class="datatable-footer_pagination">
      <datatable-pager
        [page]="curPage"
        [size]="pageSize"
        [count]="rowCount"
        [hidden]="false"
        (change)="table.onFooterPage($event)">
      </datatable-pager>
      <div class="page-limit-container">
        <select (change)="onLimitChange($event.target.value)" class="page-limit">
          <option
            *ngFor="let option of pageLimitOptions"
            [value]="option.value"
            [selected]="option.value == currentPageLimit"
          >
            {{option.value}} per page
          </option>
        </select>
      </div>
    </div>
  </ng-template>
</ngx-datatable-footer>
```

**Comment by t-p-l-k** [comment]
@dylandrollut well, basically `@ViewChild(DatatableComponent) private table: DatatableComponent;` gives you a pointer to the table. DatatableComponent has `limit` attribute which defines number of rows per page. In my example I change it directly but you can probably do the same by binding a variable in the template:
```html
<ngx-datatable
  [rows]='rows'
  [limit]='pageLimit'
  [columns]='[{name:"Name"},{name:"Gender"},{name:"Company"}]'
  [columnMode]='"force"'
  [headerHeight]='50'
  [footerHeight]='50'
  [rowHeight]='"auto"'>
</ngx-datatable>
```
I thought that it doesn't matter since you still need a pointer to the table so you can call `recalculate()` method.
```typescript
setTimeout(() => {
  if (this.table.bodyComponent.temp.length <= 0) {
    this.table.offset = Math.floor((this.table.rowCount - 1) / this.table.limit);
  }
});
```
This is a hackish way to switch active page to the last one.
`this.table.bodyComponent.temp` is an array of currently visible rows if you're using pagination.
When you have 100 items total and 5 items per page then you have 20 pages.
If you go to the 20th page and switch page limit to 50 items per page then you'll only have 2 pages.
`this.table.offset = Math.floor((this.table.rowCount - 1) / this.table.limit);` changes active page to the last page available (2 in this example).
This was only tested with client-side pagination and I have no idea what's going to happen if you use it with server-side. You can just change offset to 0 so when you change page limit your paging will reset. It will give protection from navigating to unexisting page and will work with server-side pagination I think.

**Comment by dylandrollut** [comment]
Thank you for the reply @t-p-l-k. I actually did bind it to a variable for the drop-down menu. Any idea on how to do that but with two drop-downs and two tables on the same page?

**Comment by t-p-l-k** [comment]
@dylandrollut move it to a separate component?

**Comment by mvhecke** [comment]
I think is can be a valuable feature, especially for large datasets. But it shouldn't be enabled by default as most applications don't allow you to do this.

**Comment by Muzaeed** [comment]
I am trying with pagination using ngx-datable, where my html goes like this:
<ngx-datatable [rows]="allManageTicketsEvents" [columns]="manageTicketColums" [columnMode]="'flex'" [headerHeight]="30" [footerHeight]="15" [rowHeight]="'auto'" [externalPaging]="true" [count]="page.totalElements" [offset]="page.pageNumber" [limit]="page.size"
                (page)='setPage($event)'>

                <ngx-datatable-column name="{{'lbl_date' | translate:lang}}" [flexGrow]="1">
                    <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
                        <span>{{row['date']}}</span>
                    </ng-template>
                </ngx-datatable-column>
                <ngx-datatable-column name="{{'lbl_time' | translate:lang}}" [flexGrow]="1">
                    <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
                        <span>{{row['time']}}</span>
                    </ng-template>
                </ngx-datatable-column>
                <ngx-datatable-column name="{{'lbl_event' | translate:lang}}" [flexGrow]="3">
                    <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
                        <span>{{row['eventName']}}</span>
                    </ng-template>
                </ngx-datatable-column>
                <ngx-datatable-column name="{{'lbl_location' | translate:lang}}" [flexGrow]="2">
                    <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
                        <span>{{row['location']}}</span>
                    </ng-template>
                </ngx-datatable-column>
                <ngx-datatable-column name="{{'lbl_type' | translate:lang}}" [flexGrow]="2">
                    <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
                        <span>{{row['type']}}</span>
                    </ng-template>
                </ngx-datatable-column>
                <ngx-datatable-column name="{{'lbl_season' | translate:lang}}" [flexGrow]="1">
                    <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
                        <span>{{row['season']}}</span>
                    </ng-template>
                </ngx-datatable-column>
                <ngx-datatable-column name="{{'lbl_available' | translate:lang}}" [flexGrow]="1">
                    <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
                        <span>{{row['available']}}</span>
                    </ng-template>
                </ngx-datatable-column>
                <ngx-datatable-column name="{{'lbl_reserved' | translate:lang}}" [flexGrow]="1">
                    <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
                        <span>{{row['reserved']}}</span>
                    </ng-template>
                </ngx-datatable-column>               
            </ngx-datatable>


And in the component what I have done is:
private page = {
    size: 20,
    totalElements: 0,
    totalPages: 0,
    pageNumber: 0,
    nextPage: 20
  };
  getManageTickets(): void {
    console.log("invoking getManageTickets");
    console.log(this.page);
    this.manageTicketService.getUpcomingEvents(this.page)
      .subscribe((data) => {          
          this.allManageTicketsEvents = Object.assign([]);        
          this.page.totalElements = data.total_events;
          data.EventLists.forEach(value => {
            const model = new ManageTickets(value);
            model.date = this.transformDate(model.date);
            model.time = this.transformTime(model.date);          
            this.allManageTicketsEvents.push(model);          
          });                              
      });
  }
ngOnInit() {    
    this.setPage({ offset: 0 });       
  }
 setPage(pageInfo) {
    this.page.pageNumber = pageInfo.offset;
    this.page.nextPage = (pageInfo.offset * pageInfo.pageSize + pageInfo.limit) || 20;
    this.getManageTickets();  
  } 

Where there is some problem in displaying the data when I try to load the data of second page in ngx-datatable can you any one help me with this?

**Comment by irco** [comment]
Was the original feature request ever looked into? I was interested in displaying a much smaller number of pages in the paginator to avoid overflowing.

**Comment by t-p-l-k** [comment]
@irco I've implemented it in my project, I can share my code here but I don't have time to test everything and create a PR.

**Comment by wizarrc** [comment]
Possibly related. https://github.com/swimlane/ngx-datatable/issues/963

I fixed a bug that didn't allow you to bind the `limit` and it was only allowed to be set once without a workaround. It now updates when you change `limit' from the template.

I'm assuming you want a more customizable pager though.

**Comment by irco** [comment]
@t-p-l-k would love to see what you did. I might have the time to do a pr if this is something desired.

**Comment by duard** [comment]
@t-p-l-k could you share your css for for this pagination ?

**Comment by mcakar1993** [comment]
I am using ngx-datatable.If I change  this.offset = 0 to change page number as 1 and if i change this.limit = 10 to limit list of page to ten dynamically.
But if i use  footer option then my pager not showing. Is any options? My footer code here

<ngx-datatable-footer>
    <ng-template 
      let-curPage="curPage" 
      let-offset="offset" 
      let-pageSize="pageSize" 
      let-rowCount="rowCount" 
      let-selectedCount="selectedCount" 
      ngx-datatable-footer-template>
    </ng-template>
    <datatable-pager 
      [count]="rowCount" 
      [page]="curPage" 
      [size]="pageSize" 
      (change)="handlePageChange($event)">
    </datatable-pager>
  </ngx-datatable-footer>

**Comment by mcakar1993** [comment]
<ngx-datatable-footer>
    <ng-template 
      let-curPage="curPage" 
      let-offset="offset" 
      let-pageSize="pageSize" 
      let-rowCount="rowCount" 
      let-selectedCount="selectedCount" 
      ngx-datatable-footer-template>
    </ng-template>
    <datatable-pager 
      [count]="rowCount" 
      [page]="curPage" 
      [size]="pageSize" 
      (change)="handlePageChange($event)">
    </datatable-pager>
  </ngx-datatable-footer>

**Comment by mcakar1993** [comment]
<ngx-datatable-footer>
    <ng-template 
      let-curPage="curPage" 
      let-offset="offset" 
      let-pageSize="pageSize" 
      let-rowCount="rowCount" 
      let-selectedCount="selectedCount" 
      ngx-datatable-footer-template>
    </ng-template>
    <datatable-pager 
      [count]="rowCount" 
      [page]="curPage" 
      [size]="pageSize" 
      (change)="handlePageChange($event)">
    </datatable-pager>
  </ngx-datatable-footer>

**Comment by mcakar1993** [comment]
<ngx-datatable-footer>

**Comment by amalasquezm** [comment]
Hello, 
I think it would help to can set the maximun of custom number of pages. Currently it's hardcoded to display 5 pages always.

const maxSize = 5;

 Looks messy for mobile.
![image](https://user-images.githubusercontent.com/11402664/32393465-8fec91b4-c0a7-11e7-9dfe-47ae9f8c34ad.png)

**Comment by amalasquezm** [comment]
You can prevent that using styles. I just fixed using this:

`@media (max-width: 560px) {
    .ngx-datatable .datatable-footer .datatable-pager .pager li.pages {
        display: none !important;
    }
}`

**Comment by cole-paciano** [comment]
@t-p-l-k : Not sure if you're still checking this page, but would love to know how you were able to override the 'const maxSize = 5' statement.  I really need to set it to 3 due to limited horizontal space at lower resolutions (as you illustrated previously with your screenshots above) but can't figure out how to accomplish that since the calcPages() function only has one parameter (not the one I need) as well as maxSize is set as a constant.

**Comment by t-p-l-k** [comment]
@cole-paciano hello!

I don't use ngx-datatable anymore really, I usually implement my own data grids based on angular/cdk DataTable.

But I found my old implementation and updated it to work with current version of ngx-datatable, here you go: https://stackblitz.com/edit/angular-ngx-datatable-custom-paginator

There are two dropdowns to change rows per page and visible pages in paginator. Custom paginator is basically ngx-datatable's paginator with additional `visiblePagesCount` input and updated `calcPages` method.

**Comment by t-p-l-k** [comment]
@duard Hi! I'm sorry for such late reply. I don't have time to clean it up, but here's what I've got:
```scss
@import '~@swimlane/ngx-datatable/release/index.css';
@import '~@swimlane/ngx-datatable/release/themes/material.css';
@import '~@swimlane/ngx-datatable/release/assets/icons.css';
@import './shared/variables';
@import './shared/breakpoints';

// Component styles are so messed up that it's impossible
// to override them without breaking style guide.

/* stylelint-disable */
.ngx-datatable.material.single-selection .datatable-body-row.active,
.ngx-datatable.material.single-selection .datatable-body-row.active .datatable-row-group,
.ngx-datatable.material.multi-selection .datatable-body-row.active,
.ngx-datatable.material.multi-selection .datatable-body-row.active .datatable-row-group,
.ngx-datatable.material.multi-click-selection .datatable-body-row.active,
.ngx-datatable.material.multi-click-selection .datatable-body-row.active .datatable-row-group {
  background-color: #54af3b;
  color: #fff;

  &:hover {
    background-color: #55b93c;
    color: #fff;
  }
}

.ngx-datatable.material {

  .progress-linear {
    position: fixed !important;
    bottom: 0px;
  }

  .datatable-footer_scroll-to-top {
    margin: 1em;

    .scroll-to-top-button {
      padding: 0.5em 1em;
      color: #fff;
      background-color: #4d87ea;
    }
  }

  .datatable-header {
    background-color: #383a3c;
  }

  .datatable-header-cell-label {
    color: #fff;
    cursor: pointer;
  }

  .datatable-body-cell-label {
    cursor: default;
  }

  .datatable-footer {
    font-size: 1em;

    .datatable-footer_pagination {
      width: 100%;
      padding: 0.5em 1em;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
  }

  .glp-datatable-pager {
    flex: none;
    margin-right: 1em;
    margin-left: 0;
    text-align: initial;

    ul {
      display: flex;
      flex-direction: row;
      flex-wrap: nowrap;
    }

    li {
      width: 2.5em;
      height: 2.5em;
      margin-right: 0.3em;
      cursor: pointer;

      &.active {
        font-weight: bold;
      }

      &.disabled {
        opacity: 0.6;
      }

      &.nav {
        background-color: #e68628;
        color: #fff;

        a {
          font-size: 1.5em;
        }
      }

      &.pages {
        background-color: #e6e6e6;
        display: none;

        @include gt-xs {
          display: inherit;
        }
      }
    }

    a {
      display: flex;
      justify-content: center;
      align-items: center;
      width: 100%;
      height: 100%;
    }
  }

  .datatable-footer__page-limit {
    padding: 0.4em;
    font-size: 1.2em;
    width: 10em;
  }

  &.scroll-vertical {
    max-height: 90vh;
    min-height: 20em;
  }

  ::-webkit-scrollbar {
    width: 0.35em;
    height: 0.35em;
  }

  ::-webkit-scrollbar-thumb {
    background-color: transparent;
  }

  ::-webkit-scrollbar-thumb:vertical {
    border-left: 0.1em solid $scrollbar-background-color;
  }

  ::-webkit-scrollbar-thumb:horizontal {
    border-top: 0.1em solid $scrollbar-background-color;
  }

  ::-webkit-scrollbar-track {
    background-color: transparent;
  }
}
```
Related HTML:
```html
    <ngx-datatable-footer>
      <ng-template
        let-rowCount="rowCount"
        let-pageSize="pageSize"
        let-selectedCount="selectedCount"
        let-curPage="curPage"
        let-offset="offset"
        ngx-datatable-footer-template
      >
        <div class="datatable-footer_pagination">
          <glp-datatable-pager
            [page]="curPage"
            [visiblePagesCount]="3"
            [size]="pageSize"
            [count]="rowCount"
            [hidden]="false"
            (change)="table.onFooterPage($event)">
          </glp-datatable-pager>
          <div class="datatable-footer__page-limit-container">
            <select (change)="onLimitChange($event.target.value)" class="datatable-footer__page-limit">
              <option
                *ngFor="let option of pageLimitOptions"
                [value]="option.value"
                [selected]="option.value == currentPageLimit"
              >
                {{option.value}} {{ 'COMPONENTS.DATATABLE.PER_PAGE' | translate }}
              </option>
            </select>
          </div>
        </div>
      </ng-template>
    </ngx-datatable-footer>
```
